-- AlterType: Add new AuditAction values
-- These must run outside a transaction (PostgreSQL limitation)

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LINE_PAYMENT_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LINE_PAYMENT_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LINE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PAYMENT_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PAYMENT_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPENSE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EXPENSE_CATEGORY_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OWNER_WITHDRAWAL_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'OWNER_WITHDRAWAL_DELETED';
