import type { ISODateString, UUID } from "./common";
export type AuditAction =
    | "LOGIN" | "LOGIN_FAILED" | "PACKAGE_CREATED" | "PACKAGE_UPDATED"
    | "INVENTORY_ADDED" | "INVENTORY_ADJUSTED" | "INVENTORY_RETURNED" | "INVENTORY_BATCH_UPDATED" | "INVENTORY_BATCH_DELETED"
    | "DISTRIBUTOR_CREATED" | "DISTRIBUTOR_UPDATED" | "DISTRIBUTOR_ACTIVATED" | "DISTRIBUTOR_DEACTIVATED"
    | "SALE_CREATED" | "SALE_CANCELLED" | "SALE_UPDATED"
    | "PAYMENT_CREATED" | "PAYMENT_UPDATED" | "PAYMENT_DELETED" | "PAYMENT_REVERSED"
    | "LINE_CREATED" | "LINE_UPDATED" | "LINE_DELETED"
    | "LINE_ACTIVATED" | "LINE_DEACTIVATED"
    | "LINE_PAYMENT_CREATED" | "LINE_PAYMENT_UPDATED" | "LINE_PAYMENT_DELETED" | "LINE_PAYMENT_REVERSED"
    | "EXPENSE_CREATED" | "EXPENSE_UPDATED" | "EXPENSE_REVERSED" | "EXPENSE_DELETED"
    | "EXPENSE_CATEGORY_CREATED" | "EXPENSE_CATEGORY_UPDATED"
    | "EXPENSE_CATEGORY_ACTIVATED" | "EXPENSE_CATEGORY_DEACTIVATED" | "EXPENSE_CATEGORY_DELETED"
    | "OWNER_WITHDRAWAL_CREATED" | "OWNER_WITHDRAWAL_UPDATED" | "OWNER_WITHDRAWAL_DELETED" | "OWNER_WITHDRAWAL_REVERSED"
    | "CASH_MANUAL_IN" | "CASH_MANUAL_OUT"
    | "CASH_CLOSING_CREATED"
    | "BACKUP_CREATED" | "BACKUP_RESTORED" | "BACKUP_EXPORTED"
    | "BACKUP_DELETED" | "BACKUPS_PURGED"
    | "SETTINGS_UPDATED" | "PASSWORD_CHANGED";
export interface AuditLog { id: UUID; userId: UUID; userEmail: string | null; action: AuditAction; entityType: string; entityId: UUID | null; oldValues: Record<string, unknown> | null; newValues: Record<string, unknown> | null; ipAddress: string | null; userAgent: string | null; createdAt: ISODateString; }
