ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'INVENTORY_BATCH_UPDATED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'INVENTORY_BATCH_DELETED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'DISTRIBUTOR_ACTIVATED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'DISTRIBUTOR_DEACTIVATED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'SALE_UPDATED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'PAYMENT_UPDATED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'PAYMENT_DELETED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'LINE_ACTIVATED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'LINE_DEACTIVATED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'LINE_PAYMENT_UPDATED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'LINE_PAYMENT_DELETED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'LINE_DELETED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'EXPENSE_DELETED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'EXPENSE_CATEGORY_CREATED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'EXPENSE_CATEGORY_UPDATED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'EXPENSE_CATEGORY_ACTIVATED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'EXPENSE_CATEGORY_DEACTIVATED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'EXPENSE_CATEGORY_DELETED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'OWNER_WITHDRAWAL_UPDATED';

ALTER TYPE "public"."AuditAction"
ADD VALUE IF NOT EXISTS 'OWNER_WITHDRAWAL_DELETED';